name: Accessibility Check

on: [push, pull_request]

jobs:
  accessibility:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: lab12
        run: npm install

      - name: Build project
        working-directory: lab12
        run: npm run build

      - name: Start server in background
        working-directory: lab12
        run: npm run preview & 
        
      - name: Wait for server
        run: npx wait-on http://localhost:4173

      - name: Run Accessibility Tests
        working-directory: lab12
        run: npx pa11y-ci